#!/bin/sh
host=https://raw.github.com/nisshiee/Git-Hooks
if [[ $(git rev-parse --is-bare-repository) == true ]]; then
    echo "please run on your working tree"
    exit 1
fi

cd $(git rev-parse --show-toplevel)
for i in common.sh commit-msg pre-commit; do
    echo $i
    curl -k -o .git/hooks/$i $host/master/$i
    chmod a+x .git/hooks/$i
done
